#!/bin/sh -e

URL=https://raw.githubusercontent.com/metabrainz/musicbrainz-server/master/root/types/edit_type_ids.js
OUT=types_gen.go

tmpfile=$(mktemp --tmpdir mbstats_gen_types.XXXXXX)
trap "rm '$tmpfile'" EXIT
curl --silent --show-error "$URL" >"$tmpfile"

cat >"$OUT" <<EOF
// This file was automatically generated by gen_types.sh from
// ${URL}
// and should not be edited manually.

package mbstats

const (
EOF

<"$tmpfile" \
  sed -nre 's/^declare type (EDIT_[_A-Z]+)_T = ([0-9]+);$/\1 EditType = \2/p' | \
  sort -n -k 4 >>"$OUT"

cat >>"$OUT" <<EOF
)

var editTypeNames = map[EditType]string{
EOF

<"$tmpfile" \
  sed -nre 's/^declare type EDIT_([_A-Z]+)_T .*$/EDIT_\1: "\1",/p' | \
  sort >>"$OUT"

cat >>"$OUT" <<EOF
}
EOF

gofmt -w "$OUT"
