// This file was automatically generated by gen_types.sh from
// https://raw.githubusercontent.com/metabrainz/musicbrainz-server/master/root/types/edit_type_ids.js
// and should not be edited manually.

package mbstats

const (
	EDIT_ARTIST_CREATE                         EditType = 1
	EDIT_ARTIST_EDIT                           EditType = 2
	EDIT_ARTIST_DELETE                         EditType = 3
	EDIT_ARTIST_MERGE                          EditType = 4
	EDIT_ARTIST_ADD_ANNOTATION                 EditType = 5
	EDIT_ARTIST_ADD_ALIAS                      EditType = 6
	EDIT_ARTIST_DELETE_ALIAS                   EditType = 7
	EDIT_ARTIST_EDIT_ALIAS                     EditType = 8
	EDIT_ARTIST_EDITCREDIT                     EditType = 9
	EDIT_LABEL_CREATE                          EditType = 10
	EDIT_LABEL_EDIT                            EditType = 11
	EDIT_LABEL_DELETE                          EditType = 13
	EDIT_LABEL_MERGE                           EditType = 14
	EDIT_LABEL_ADD_ANNOTATION                  EditType = 15
	EDIT_LABEL_ADD_ALIAS                       EditType = 16
	EDIT_LABEL_DELETE_ALIAS                    EditType = 17
	EDIT_LABEL_EDIT_ALIAS                      EditType = 18
	EDIT_RELEASEGROUP_CREATE                   EditType = 20
	EDIT_RELEASEGROUP_EDIT                     EditType = 21
	EDIT_RELEASEGROUP_SET_COVER_ART            EditType = 22
	EDIT_RELEASEGROUP_DELETE                   EditType = 23
	EDIT_RELEASEGROUP_MERGE                    EditType = 24
	EDIT_RELEASEGROUP_ADD_ANNOTATION           EditType = 25
	EDIT_RELEASEGROUP_ADD_ALIAS                EditType = 26
	EDIT_RELEASEGROUP_DELETE_ALIAS             EditType = 27
	EDIT_RELEASEGROUP_EDIT_ALIAS               EditType = 28
	EDIT_RELEASE_CREATE                        EditType = 31
	EDIT_RELEASE_EDIT                          EditType = 32
	EDIT_RELEASE_MOVE                          EditType = 33
	EDIT_RELEASE_ADDRELEASELABEL               EditType = 34
	EDIT_RELEASE_ADD_ANNOTATION                EditType = 35
	EDIT_RELEASE_DELETERELEASELABEL            EditType = 36
	EDIT_RELEASE_EDITRELEASELABEL              EditType = 37
	EDIT_RELEASE_CHANGE_QUALITY                EditType = 38
	EDIT_RELEASE_EDIT_BARCODES                 EditType = 39
	EDIT_WORK_CREATE                           EditType = 41
	EDIT_WORK_EDIT                             EditType = 42
	EDIT_WORK_DELETE                           EditType = 43
	EDIT_WORK_MERGE                            EditType = 44
	EDIT_WORK_ADD_ANNOTATION                   EditType = 45
	EDIT_WORK_ADD_ALIAS                        EditType = 46
	EDIT_WORK_DELETE_ALIAS                     EditType = 47
	EDIT_WORK_EDIT_ALIAS                       EditType = 48
	EDIT_WORK_ADD_ISWCS                        EditType = 49
	EDIT_MEDIUM_CREATE                         EditType = 51
	EDIT_MEDIUM_EDIT                           EditType = 52
	EDIT_MEDIUM_DELETE                         EditType = 53
	EDIT_MEDIUM_REMOVE_DISCID                  EditType = 54
	EDIT_MEDIUM_ADD_DISCID                     EditType = 55
	EDIT_MEDIUM_MOVE_DISCID                    EditType = 56
	EDIT_SET_TRACK_LENGTHS                     EditType = 58
	EDIT_PLACE_CREATE                          EditType = 61
	EDIT_PLACE_EDIT                            EditType = 62
	EDIT_PLACE_DELETE                          EditType = 63
	EDIT_PLACE_MERGE                           EditType = 64
	EDIT_PLACE_ADD_ANNOTATION                  EditType = 65
	EDIT_PLACE_ADD_ALIAS                       EditType = 66
	EDIT_PLACE_DELETE_ALIAS                    EditType = 67
	EDIT_PLACE_EDIT_ALIAS                      EditType = 68
	EDIT_RECORDING_CREATE                      EditType = 71
	EDIT_RECORDING_EDIT                        EditType = 72
	EDIT_RECORDING_DELETE                      EditType = 73
	EDIT_RECORDING_MERGE                       EditType = 74
	EDIT_RECORDING_ADD_ANNOTATION              EditType = 75
	EDIT_RECORDING_ADD_ISRCS                   EditType = 76
	EDIT_RECORDING_REMOVE_ISRC                 EditType = 78
	EDIT_AREA_CREATE                           EditType = 81
	EDIT_AREA_EDIT                             EditType = 82
	EDIT_AREA_DELETE                           EditType = 83
	EDIT_AREA_MERGE                            EditType = 84
	EDIT_AREA_ADD_ANNOTATION                   EditType = 85
	EDIT_AREA_ADD_ALIAS                        EditType = 86
	EDIT_AREA_DELETE_ALIAS                     EditType = 87
	EDIT_AREA_EDIT_ALIAS                       EditType = 88
	EDIT_RELATIONSHIP_CREATE                   EditType = 90
	EDIT_RELATIONSHIP_EDIT                     EditType = 91
	EDIT_RELATIONSHIP_DELETE                   EditType = 92
	EDIT_RELATIONSHIP_REMOVE_LINK_TYPE         EditType = 93
	EDIT_RELATIONSHIP_REMOVE_LINK_ATTRIBUTE    EditType = 94
	EDIT_RELATIONSHIP_EDIT_LINK_TYPE           EditType = 95
	EDIT_RELATIONSHIP_ADD_TYPE                 EditType = 96
	EDIT_RELATIONSHIP_ATTRIBUTE                EditType = 97
	EDIT_RELATIONSHIP_ADD_ATTRIBUTE            EditType = 98
	EDIT_RELATIONSHIPS_REORDER                 EditType = 99
	EDIT_URL_EDIT                              EditType = 101
	EDIT_WIKIDOC_CHANGE                        EditType = 120
	EDIT_INSTRUMENT_CREATE                     EditType = 131
	EDIT_INSTRUMENT_EDIT                       EditType = 132
	EDIT_INSTRUMENT_DELETE                     EditType = 133
	EDIT_INSTRUMENT_MERGE                      EditType = 134
	EDIT_INSTRUMENT_ADD_ANNOTATION             EditType = 135
	EDIT_INSTRUMENT_ADD_ALIAS                  EditType = 136
	EDIT_INSTRUMENT_DELETE_ALIAS               EditType = 137
	EDIT_INSTRUMENT_EDIT_ALIAS                 EditType = 138
	EDIT_SERIES_CREATE                         EditType = 140
	EDIT_SERIES_EDIT                           EditType = 141
	EDIT_SERIES_DELETE                         EditType = 142
	EDIT_SERIES_MERGE                          EditType = 143
	EDIT_SERIES_ADD_ANNOTATION                 EditType = 144
	EDIT_SERIES_ADD_ALIAS                      EditType = 145
	EDIT_SERIES_DELETE_ALIAS                   EditType = 146
	EDIT_SERIES_EDIT_ALIAS                     EditType = 147
	EDIT_EVENT_CREATE                          EditType = 150
	EDIT_EVENT_EDIT                            EditType = 151
	EDIT_EVENT_DELETE                          EditType = 152
	EDIT_EVENT_MERGE                           EditType = 153
	EDIT_EVENT_ADD_ANNOTATION                  EditType = 154
	EDIT_EVENT_ADD_ALIAS                       EditType = 155
	EDIT_EVENT_DELETE_ALIAS                    EditType = 156
	EDIT_EVENT_EDIT_ALIAS                      EditType = 157
	EDIT_GENRE_CREATE                          EditType = 160
	EDIT_GENRE_EDIT                            EditType = 161
	EDIT_GENRE_DELETE                          EditType = 162
	EDIT_GENRE_ADD_ANNOTATION                  EditType = 164
	EDIT_GENRE_ADD_ALIAS                       EditType = 165
	EDIT_GENRE_DELETE_ALIAS                    EditType = 166
	EDIT_GENRE_EDIT_ALIAS                      EditType = 167
	EDIT_HISTORIC_EDIT_RELEASE_NAME            EditType = 201
	EDIT_HISTORIC_EDIT_TRACKNAME               EditType = 204
	EDIT_HISTORIC_EDIT_TRACKNUM                EditType = 205
	EDIT_HISTORIC_ADD_TRACK                    EditType = 207
	EDIT_HISTORIC_MOVE_RELEASE                 EditType = 208
	EDIT_HISTORIC_SAC_TO_MAC                   EditType = 209
	EDIT_HISTORIC_CHANGE_TRACK_ARTIST          EditType = 210
	EDIT_HISTORIC_REMOVE_TRACK                 EditType = 211
	EDIT_HISTORIC_REMOVE_RELEASE               EditType = 212
	EDIT_HISTORIC_MAC_TO_SAC                   EditType = 213
	EDIT_HISTORIC_ADD_RELEASE                  EditType = 216
	EDIT_HISTORIC_ADD_TRACK_KV                 EditType = 218
	EDIT_HISTORIC_REMOVE_DISCID                EditType = 220
	EDIT_HISTORIC_MOVE_DISCID                  EditType = 221
	EDIT_HISTORIC_MERGE_RELEASE                EditType = 223
	EDIT_HISTORIC_REMOVE_RELEASES              EditType = 224
	EDIT_HISTORIC_MERGE_RELEASE_MAC            EditType = 225
	EDIT_HISTORIC_EDIT_RELEASE_ATTRS           EditType = 226
	EDIT_HISTORIC_EDIT_RELEASE_EVENTS_OLD      EditType = 229
	EDIT_HISTORIC_ADD_RELEASE_ANNOTATION       EditType = 231
	EDIT_HISTORIC_ADD_DISCID                   EditType = 232
	EDIT_HISTORIC_ADD_LINK                     EditType = 233
	EDIT_HISTORIC_EDIT_LINK                    EditType = 234
	EDIT_HISTORIC_REMOVE_LINK                  EditType = 235
	EDIT_HISTORIC_EDIT_LINK_TYPE               EditType = 237
	EDIT_HISTORIC_REMOVE_LINK_TYPE             EditType = 238
	EDIT_HISTORIC_EDIT_RELEASE_LANGUAGE        EditType = 244
	EDIT_HISTORIC_EDIT_TRACK_LENGTH            EditType = 245
	EDIT_HISTORIC_ADD_RELEASE_EVENTS           EditType = 249
	EDIT_HISTORIC_EDIT_RELEASE_EVENTS          EditType = 250
	EDIT_HISTORIC_REMOVE_RELEASE_EVENTS        EditType = 251
	EDIT_HISTORIC_CHANGE_ARTIST_QUALITY        EditType = 252
	EDIT_HISTORIC_SET_TRACK_LENGTHS_FROM_CDTOC EditType = 253
	EDIT_HISTORIC_REMOVE_LABEL_ALIAS           EditType = 262
	EDIT_HISTORIC_CHANGE_RELEASE_QUALITY       EditType = 263
	EDIT_HISTORIC_CHANGE_RELEASE_GROUP         EditType = 273
	EDIT_RELEASE_DELETE                        EditType = 310
	EDIT_RELEASE_MERGE                         EditType = 311
	EDIT_RELEASE_ARTIST                        EditType = 312
	EDIT_RELEASE_REORDER_MEDIUMS               EditType = 313
	EDIT_RELEASE_ADD_COVER_ART                 EditType = 314
	EDIT_RELEASE_REMOVE_COVER_ART              EditType = 315
	EDIT_RELEASE_EDIT_COVER_ART                EditType = 316
	EDIT_RELEASE_REORDER_COVER_ART             EditType = 317
	EDIT_RELEASE_ADD_ALIAS                     EditType = 318
	EDIT_RELEASE_DELETE_ALIAS                  EditType = 319
	EDIT_RELEASE_EDIT_ALIAS                    EditType = 320
	EDIT_WORK_REMOVE_ISWC                      EditType = 410
	EDIT_RECORDING_ADD_ALIAS                   EditType = 711
	EDIT_RECORDING_DELETE_ALIAS                EditType = 712
	EDIT_RECORDING_EDIT_ALIAS                  EditType = 713
)

var editTypeNames = map[EditType]string{
	EDIT_AREA_ADD_ALIAS:                        "AREA_ADD_ALIAS",
	EDIT_AREA_ADD_ANNOTATION:                   "AREA_ADD_ANNOTATION",
	EDIT_AREA_CREATE:                           "AREA_CREATE",
	EDIT_AREA_DELETE_ALIAS:                     "AREA_DELETE_ALIAS",
	EDIT_AREA_DELETE:                           "AREA_DELETE",
	EDIT_AREA_EDIT_ALIAS:                       "AREA_EDIT_ALIAS",
	EDIT_AREA_EDIT:                             "AREA_EDIT",
	EDIT_AREA_MERGE:                            "AREA_MERGE",
	EDIT_ARTIST_ADD_ALIAS:                      "ARTIST_ADD_ALIAS",
	EDIT_ARTIST_ADD_ANNOTATION:                 "ARTIST_ADD_ANNOTATION",
	EDIT_ARTIST_CREATE:                         "ARTIST_CREATE",
	EDIT_ARTIST_DELETE_ALIAS:                   "ARTIST_DELETE_ALIAS",
	EDIT_ARTIST_DELETE:                         "ARTIST_DELETE",
	EDIT_ARTIST_EDIT_ALIAS:                     "ARTIST_EDIT_ALIAS",
	EDIT_ARTIST_EDIT:                           "ARTIST_EDIT",
	EDIT_ARTIST_EDITCREDIT:                     "ARTIST_EDITCREDIT",
	EDIT_ARTIST_MERGE:                          "ARTIST_MERGE",
	EDIT_EVENT_ADD_ALIAS:                       "EVENT_ADD_ALIAS",
	EDIT_EVENT_ADD_ANNOTATION:                  "EVENT_ADD_ANNOTATION",
	EDIT_EVENT_CREATE:                          "EVENT_CREATE",
	EDIT_EVENT_DELETE_ALIAS:                    "EVENT_DELETE_ALIAS",
	EDIT_EVENT_DELETE:                          "EVENT_DELETE",
	EDIT_EVENT_EDIT_ALIAS:                      "EVENT_EDIT_ALIAS",
	EDIT_EVENT_EDIT:                            "EVENT_EDIT",
	EDIT_EVENT_MERGE:                           "EVENT_MERGE",
	EDIT_GENRE_ADD_ALIAS:                       "GENRE_ADD_ALIAS",
	EDIT_GENRE_ADD_ANNOTATION:                  "GENRE_ADD_ANNOTATION",
	EDIT_GENRE_CREATE:                          "GENRE_CREATE",
	EDIT_GENRE_DELETE_ALIAS:                    "GENRE_DELETE_ALIAS",
	EDIT_GENRE_DELETE:                          "GENRE_DELETE",
	EDIT_GENRE_EDIT_ALIAS:                      "GENRE_EDIT_ALIAS",
	EDIT_GENRE_EDIT:                            "GENRE_EDIT",
	EDIT_HISTORIC_ADD_DISCID:                   "HISTORIC_ADD_DISCID",
	EDIT_HISTORIC_ADD_LINK:                     "HISTORIC_ADD_LINK",
	EDIT_HISTORIC_ADD_RELEASE_ANNOTATION:       "HISTORIC_ADD_RELEASE_ANNOTATION",
	EDIT_HISTORIC_ADD_RELEASE_EVENTS:           "HISTORIC_ADD_RELEASE_EVENTS",
	EDIT_HISTORIC_ADD_RELEASE:                  "HISTORIC_ADD_RELEASE",
	EDIT_HISTORIC_ADD_TRACK:                    "HISTORIC_ADD_TRACK",
	EDIT_HISTORIC_ADD_TRACK_KV:                 "HISTORIC_ADD_TRACK_KV",
	EDIT_HISTORIC_CHANGE_ARTIST_QUALITY:        "HISTORIC_CHANGE_ARTIST_QUALITY",
	EDIT_HISTORIC_CHANGE_RELEASE_GROUP:         "HISTORIC_CHANGE_RELEASE_GROUP",
	EDIT_HISTORIC_CHANGE_RELEASE_QUALITY:       "HISTORIC_CHANGE_RELEASE_QUALITY",
	EDIT_HISTORIC_CHANGE_TRACK_ARTIST:          "HISTORIC_CHANGE_TRACK_ARTIST",
	EDIT_HISTORIC_EDIT_LINK:                    "HISTORIC_EDIT_LINK",
	EDIT_HISTORIC_EDIT_LINK_TYPE:               "HISTORIC_EDIT_LINK_TYPE",
	EDIT_HISTORIC_EDIT_RELEASE_ATTRS:           "HISTORIC_EDIT_RELEASE_ATTRS",
	EDIT_HISTORIC_EDIT_RELEASE_EVENTS:          "HISTORIC_EDIT_RELEASE_EVENTS",
	EDIT_HISTORIC_EDIT_RELEASE_EVENTS_OLD:      "HISTORIC_EDIT_RELEASE_EVENTS_OLD",
	EDIT_HISTORIC_EDIT_RELEASE_LANGUAGE:        "HISTORIC_EDIT_RELEASE_LANGUAGE",
	EDIT_HISTORIC_EDIT_RELEASE_NAME:            "HISTORIC_EDIT_RELEASE_NAME",
	EDIT_HISTORIC_EDIT_TRACK_LENGTH:            "HISTORIC_EDIT_TRACK_LENGTH",
	EDIT_HISTORIC_EDIT_TRACKNAME:               "HISTORIC_EDIT_TRACKNAME",
	EDIT_HISTORIC_EDIT_TRACKNUM:                "HISTORIC_EDIT_TRACKNUM",
	EDIT_HISTORIC_MAC_TO_SAC:                   "HISTORIC_MAC_TO_SAC",
	EDIT_HISTORIC_MERGE_RELEASE:                "HISTORIC_MERGE_RELEASE",
	EDIT_HISTORIC_MERGE_RELEASE_MAC:            "HISTORIC_MERGE_RELEASE_MAC",
	EDIT_HISTORIC_MOVE_DISCID:                  "HISTORIC_MOVE_DISCID",
	EDIT_HISTORIC_MOVE_RELEASE:                 "HISTORIC_MOVE_RELEASE",
	EDIT_HISTORIC_REMOVE_DISCID:                "HISTORIC_REMOVE_DISCID",
	EDIT_HISTORIC_REMOVE_LABEL_ALIAS:           "HISTORIC_REMOVE_LABEL_ALIAS",
	EDIT_HISTORIC_REMOVE_LINK:                  "HISTORIC_REMOVE_LINK",
	EDIT_HISTORIC_REMOVE_LINK_TYPE:             "HISTORIC_REMOVE_LINK_TYPE",
	EDIT_HISTORIC_REMOVE_RELEASE_EVENTS:        "HISTORIC_REMOVE_RELEASE_EVENTS",
	EDIT_HISTORIC_REMOVE_RELEASE:               "HISTORIC_REMOVE_RELEASE",
	EDIT_HISTORIC_REMOVE_RELEASES:              "HISTORIC_REMOVE_RELEASES",
	EDIT_HISTORIC_REMOVE_TRACK:                 "HISTORIC_REMOVE_TRACK",
	EDIT_HISTORIC_SAC_TO_MAC:                   "HISTORIC_SAC_TO_MAC",
	EDIT_HISTORIC_SET_TRACK_LENGTHS_FROM_CDTOC: "HISTORIC_SET_TRACK_LENGTHS_FROM_CDTOC",
	EDIT_INSTRUMENT_ADD_ALIAS:                  "INSTRUMENT_ADD_ALIAS",
	EDIT_INSTRUMENT_ADD_ANNOTATION:             "INSTRUMENT_ADD_ANNOTATION",
	EDIT_INSTRUMENT_CREATE:                     "INSTRUMENT_CREATE",
	EDIT_INSTRUMENT_DELETE_ALIAS:               "INSTRUMENT_DELETE_ALIAS",
	EDIT_INSTRUMENT_DELETE:                     "INSTRUMENT_DELETE",
	EDIT_INSTRUMENT_EDIT_ALIAS:                 "INSTRUMENT_EDIT_ALIAS",
	EDIT_INSTRUMENT_EDIT:                       "INSTRUMENT_EDIT",
	EDIT_INSTRUMENT_MERGE:                      "INSTRUMENT_MERGE",
	EDIT_LABEL_ADD_ALIAS:                       "LABEL_ADD_ALIAS",
	EDIT_LABEL_ADD_ANNOTATION:                  "LABEL_ADD_ANNOTATION",
	EDIT_LABEL_CREATE:                          "LABEL_CREATE",
	EDIT_LABEL_DELETE_ALIAS:                    "LABEL_DELETE_ALIAS",
	EDIT_LABEL_DELETE:                          "LABEL_DELETE",
	EDIT_LABEL_EDIT_ALIAS:                      "LABEL_EDIT_ALIAS",
	EDIT_LABEL_EDIT:                            "LABEL_EDIT",
	EDIT_LABEL_MERGE:                           "LABEL_MERGE",
	EDIT_MEDIUM_ADD_DISCID:                     "MEDIUM_ADD_DISCID",
	EDIT_MEDIUM_CREATE:                         "MEDIUM_CREATE",
	EDIT_MEDIUM_DELETE:                         "MEDIUM_DELETE",
	EDIT_MEDIUM_EDIT:                           "MEDIUM_EDIT",
	EDIT_MEDIUM_MOVE_DISCID:                    "MEDIUM_MOVE_DISCID",
	EDIT_MEDIUM_REMOVE_DISCID:                  "MEDIUM_REMOVE_DISCID",
	EDIT_PLACE_ADD_ALIAS:                       "PLACE_ADD_ALIAS",
	EDIT_PLACE_ADD_ANNOTATION:                  "PLACE_ADD_ANNOTATION",
	EDIT_PLACE_CREATE:                          "PLACE_CREATE",
	EDIT_PLACE_DELETE_ALIAS:                    "PLACE_DELETE_ALIAS",
	EDIT_PLACE_DELETE:                          "PLACE_DELETE",
	EDIT_PLACE_EDIT_ALIAS:                      "PLACE_EDIT_ALIAS",
	EDIT_PLACE_EDIT:                            "PLACE_EDIT",
	EDIT_PLACE_MERGE:                           "PLACE_MERGE",
	EDIT_RECORDING_ADD_ALIAS:                   "RECORDING_ADD_ALIAS",
	EDIT_RECORDING_ADD_ANNOTATION:              "RECORDING_ADD_ANNOTATION",
	EDIT_RECORDING_ADD_ISRCS:                   "RECORDING_ADD_ISRCS",
	EDIT_RECORDING_CREATE:                      "RECORDING_CREATE",
	EDIT_RECORDING_DELETE_ALIAS:                "RECORDING_DELETE_ALIAS",
	EDIT_RECORDING_DELETE:                      "RECORDING_DELETE",
	EDIT_RECORDING_EDIT_ALIAS:                  "RECORDING_EDIT_ALIAS",
	EDIT_RECORDING_EDIT:                        "RECORDING_EDIT",
	EDIT_RECORDING_MERGE:                       "RECORDING_MERGE",
	EDIT_RECORDING_REMOVE_ISRC:                 "RECORDING_REMOVE_ISRC",
	EDIT_RELATIONSHIP_ADD_ATTRIBUTE:            "RELATIONSHIP_ADD_ATTRIBUTE",
	EDIT_RELATIONSHIP_ADD_TYPE:                 "RELATIONSHIP_ADD_TYPE",
	EDIT_RELATIONSHIP_ATTRIBUTE:                "RELATIONSHIP_ATTRIBUTE",
	EDIT_RELATIONSHIP_CREATE:                   "RELATIONSHIP_CREATE",
	EDIT_RELATIONSHIP_DELETE:                   "RELATIONSHIP_DELETE",
	EDIT_RELATIONSHIP_EDIT_LINK_TYPE:           "RELATIONSHIP_EDIT_LINK_TYPE",
	EDIT_RELATIONSHIP_EDIT:                     "RELATIONSHIP_EDIT",
	EDIT_RELATIONSHIP_REMOVE_LINK_ATTRIBUTE:    "RELATIONSHIP_REMOVE_LINK_ATTRIBUTE",
	EDIT_RELATIONSHIP_REMOVE_LINK_TYPE:         "RELATIONSHIP_REMOVE_LINK_TYPE",
	EDIT_RELATIONSHIPS_REORDER:                 "RELATIONSHIPS_REORDER",
	EDIT_RELEASE_ADD_ALIAS:                     "RELEASE_ADD_ALIAS",
	EDIT_RELEASE_ADD_ANNOTATION:                "RELEASE_ADD_ANNOTATION",
	EDIT_RELEASE_ADD_COVER_ART:                 "RELEASE_ADD_COVER_ART",
	EDIT_RELEASE_ADDRELEASELABEL:               "RELEASE_ADDRELEASELABEL",
	EDIT_RELEASE_ARTIST:                        "RELEASE_ARTIST",
	EDIT_RELEASE_CHANGE_QUALITY:                "RELEASE_CHANGE_QUALITY",
	EDIT_RELEASE_CREATE:                        "RELEASE_CREATE",
	EDIT_RELEASE_DELETE_ALIAS:                  "RELEASE_DELETE_ALIAS",
	EDIT_RELEASE_DELETE:                        "RELEASE_DELETE",
	EDIT_RELEASE_DELETERELEASELABEL:            "RELEASE_DELETERELEASELABEL",
	EDIT_RELEASE_EDIT_ALIAS:                    "RELEASE_EDIT_ALIAS",
	EDIT_RELEASE_EDIT_BARCODES:                 "RELEASE_EDIT_BARCODES",
	EDIT_RELEASE_EDIT_COVER_ART:                "RELEASE_EDIT_COVER_ART",
	EDIT_RELEASE_EDIT:                          "RELEASE_EDIT",
	EDIT_RELEASE_EDITRELEASELABEL:              "RELEASE_EDITRELEASELABEL",
	EDIT_RELEASEGROUP_ADD_ALIAS:                "RELEASEGROUP_ADD_ALIAS",
	EDIT_RELEASEGROUP_ADD_ANNOTATION:           "RELEASEGROUP_ADD_ANNOTATION",
	EDIT_RELEASEGROUP_CREATE:                   "RELEASEGROUP_CREATE",
	EDIT_RELEASEGROUP_DELETE_ALIAS:             "RELEASEGROUP_DELETE_ALIAS",
	EDIT_RELEASEGROUP_DELETE:                   "RELEASEGROUP_DELETE",
	EDIT_RELEASEGROUP_EDIT_ALIAS:               "RELEASEGROUP_EDIT_ALIAS",
	EDIT_RELEASEGROUP_EDIT:                     "RELEASEGROUP_EDIT",
	EDIT_RELEASEGROUP_MERGE:                    "RELEASEGROUP_MERGE",
	EDIT_RELEASEGROUP_SET_COVER_ART:            "RELEASEGROUP_SET_COVER_ART",
	EDIT_RELEASE_MERGE:                         "RELEASE_MERGE",
	EDIT_RELEASE_MOVE:                          "RELEASE_MOVE",
	EDIT_RELEASE_REMOVE_COVER_ART:              "RELEASE_REMOVE_COVER_ART",
	EDIT_RELEASE_REORDER_COVER_ART:             "RELEASE_REORDER_COVER_ART",
	EDIT_RELEASE_REORDER_MEDIUMS:               "RELEASE_REORDER_MEDIUMS",
	EDIT_SERIES_ADD_ALIAS:                      "SERIES_ADD_ALIAS",
	EDIT_SERIES_ADD_ANNOTATION:                 "SERIES_ADD_ANNOTATION",
	EDIT_SERIES_CREATE:                         "SERIES_CREATE",
	EDIT_SERIES_DELETE_ALIAS:                   "SERIES_DELETE_ALIAS",
	EDIT_SERIES_DELETE:                         "SERIES_DELETE",
	EDIT_SERIES_EDIT_ALIAS:                     "SERIES_EDIT_ALIAS",
	EDIT_SERIES_EDIT:                           "SERIES_EDIT",
	EDIT_SERIES_MERGE:                          "SERIES_MERGE",
	EDIT_SET_TRACK_LENGTHS:                     "SET_TRACK_LENGTHS",
	EDIT_URL_EDIT:                              "URL_EDIT",
	EDIT_WIKIDOC_CHANGE:                        "WIKIDOC_CHANGE",
	EDIT_WORK_ADD_ALIAS:                        "WORK_ADD_ALIAS",
	EDIT_WORK_ADD_ANNOTATION:                   "WORK_ADD_ANNOTATION",
	EDIT_WORK_ADD_ISWCS:                        "WORK_ADD_ISWCS",
	EDIT_WORK_CREATE:                           "WORK_CREATE",
	EDIT_WORK_DELETE_ALIAS:                     "WORK_DELETE_ALIAS",
	EDIT_WORK_DELETE:                           "WORK_DELETE",
	EDIT_WORK_EDIT_ALIAS:                       "WORK_EDIT_ALIAS",
	EDIT_WORK_EDIT:                             "WORK_EDIT",
	EDIT_WORK_MERGE:                            "WORK_MERGE",
	EDIT_WORK_REMOVE_ISWC:                      "WORK_REMOVE_ISWC",
}
